CREATE TABLE STOCK_PRICE_DTLS (
    STOCK_PRICE_ID INT PRIMARY KEY,
    COMPANY_NAME VARCHAR(255),
    COMPANY_STOCK_PRICE DECIMAL(10, 2)
);

insert into STOCK_PRICE_DTLS(STOCK_PRICE_ID,COMPANY_NAME,COMPANY_STOCK_PRICE) values(101,'sbi',430.00);
insert into STOCK_PRICE_DTLS(STOCK_PRICE_ID,COMPANY_NAME,COMPANY_STOCK_PRICE) values(102,'bhel',43.00);
insert into STOCK_PRICE_DTLS(STOCK_PRICE_ID,COMPANY_NAME,COMPANY_STOCK_PRICE) values(103,'hdfc',1400.00);
insert into STOCK_PRICE_DTLS(STOCK_PRICE_ID,COMPANY_NAME,COMPANY_STOCK_PRICE) values(104,'hcl',950.00);
insert into STOCK_PRICE_DTLS(STOCK_PRICE_ID,COMPANY_NAME,COMPANY_STOCK_PRICE) values(105,'tcs',2950.00);

