spring:
  application:
    name: 01_SB_OAuth_App
  security:
    oauth2:
      client:
        registration:
          github:
						# Client id and client secret i comemnted because git security feature it is not pushing
          #  client Id: Ov23liqbXNLNCqJ1RXzb
          #  client Secret: 99a4d1c2b38109e4851b089fa64d6c85e20719b7
